# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supply_chain_processor/protobuf/record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from supply_chain_processor.protobuf import property_pb2 as supply__chain__processor_dot_protobuf_dot_property__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='supply_chain_processor/protobuf/record.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n,supply_chain_processor/protobuf/record.proto\x1a.supply_chain_processor/protobuf/property.proto\"\xcd\x01\n\x06Record\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x13\n\x0brecord_type\x18\x02 \x01(\t\x12\'\n\x06owners\x18\x03 \x03(\x0b\x32\x17.Record.AssociatedAgent\x12+\n\ncustodians\x18\x04 \x03(\x0b\x32\x17.Record.AssociatedAgent\x12\r\n\x05\x66inal\x18\x05 \x01(\x08\x1a\x36\n\x0f\x41ssociatedAgent\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"+\n\x0fRecordContainer\x12\x18\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x07.Record\"?\n\nRecordType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\nproperties\x18\x02 \x03(\x0b\x32\x0f.PropertySchema\"3\n\x13RecordTypeContainer\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.RecordTypeb\x06proto3')
  ,
  dependencies=[supply__chain__processor_dot_protobuf_dot_property__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECORD_ASSOCIATEDAGENT = _descriptor.Descriptor(
  name='AssociatedAgent',
  full_name='Record.AssociatedAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='Record.AssociatedAgent.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Record.AssociatedAgent.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=302,
)

_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_id', full_name='Record.record_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_type', full_name='Record.record_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owners', full_name='Record.owners', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custodians', full_name='Record.custodians', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final', full_name='Record.final', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RECORD_ASSOCIATEDAGENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=302,
)


_RECORDCONTAINER = _descriptor.Descriptor(
  name='RecordContainer',
  full_name='RecordContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='RecordContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=347,
)


_RECORDTYPE = _descriptor.Descriptor(
  name='RecordType',
  full_name='RecordType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RecordType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='RecordType.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=412,
)


_RECORDTYPECONTAINER = _descriptor.Descriptor(
  name='RecordTypeContainer',
  full_name='RecordTypeContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='RecordTypeContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=465,
)

_RECORD_ASSOCIATEDAGENT.containing_type = _RECORD
_RECORD.fields_by_name['owners'].message_type = _RECORD_ASSOCIATEDAGENT
_RECORD.fields_by_name['custodians'].message_type = _RECORD_ASSOCIATEDAGENT
_RECORDCONTAINER.fields_by_name['entries'].message_type = _RECORD
_RECORDTYPE.fields_by_name['properties'].message_type = supply__chain__processor_dot_protobuf_dot_property__pb2._PROPERTYSCHEMA
_RECORDTYPECONTAINER.fields_by_name['entries'].message_type = _RECORDTYPE
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['RecordContainer'] = _RECORDCONTAINER
DESCRIPTOR.message_types_by_name['RecordType'] = _RECORDTYPE
DESCRIPTOR.message_types_by_name['RecordTypeContainer'] = _RECORDTYPECONTAINER

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(

  AssociatedAgent = _reflection.GeneratedProtocolMessageType('AssociatedAgent', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_ASSOCIATEDAGENT,
    __module__ = 'supply_chain_processor.protobuf.record_pb2'
    # @@protoc_insertion_point(class_scope:Record.AssociatedAgent)
    ))
  ,
  DESCRIPTOR = _RECORD,
  __module__ = 'supply_chain_processor.protobuf.record_pb2'
  # @@protoc_insertion_point(class_scope:Record)
  ))
_sym_db.RegisterMessage(Record)
_sym_db.RegisterMessage(Record.AssociatedAgent)

RecordContainer = _reflection.GeneratedProtocolMessageType('RecordContainer', (_message.Message,), dict(
  DESCRIPTOR = _RECORDCONTAINER,
  __module__ = 'supply_chain_processor.protobuf.record_pb2'
  # @@protoc_insertion_point(class_scope:RecordContainer)
  ))
_sym_db.RegisterMessage(RecordContainer)

RecordType = _reflection.GeneratedProtocolMessageType('RecordType', (_message.Message,), dict(
  DESCRIPTOR = _RECORDTYPE,
  __module__ = 'supply_chain_processor.protobuf.record_pb2'
  # @@protoc_insertion_point(class_scope:RecordType)
  ))
_sym_db.RegisterMessage(RecordType)

RecordTypeContainer = _reflection.GeneratedProtocolMessageType('RecordTypeContainer', (_message.Message,), dict(
  DESCRIPTOR = _RECORDTYPECONTAINER,
  __module__ = 'supply_chain_processor.protobuf.record_pb2'
  # @@protoc_insertion_point(class_scope:RecordTypeContainer)
  ))
_sym_db.RegisterMessage(RecordTypeContainer)


# @@protoc_insertion_point(module_scope)
